### ISSUE TITLE
Add ScanCode (from AboutCode)

### ISSUE THREAD

**Issue by david-a-wheeler** [ivanayov/sbom-know-how#2]
Add this tool:

ScanCode (from AboutCode)
https://www.aboutcode.org/
It's an OSS tool that generates SBOMs. It supports containers, system packages, and many language packages. It can generate SPDX and CycloneDX. See the website for more info. I recently learned about this tool from Phillippe Ombredanne.

**Comment by pombredanne** [comment]
Hiya:
I am the lead maintainer for AboutCode tools and on hand to help with the entry(ies)... here is a quick picth:

- ScanCode toolkit (CLI and library) can write handles SPDX and CycloneDX - it has best in class supports for all the common application and system package formats https://github.com/nexB/scancode-toolkit/tree/develop/src/packagedcode and is the industry standard for license and origin/copyright scanning. 
ScanCode toolkit is also embedded in ORT, Tern, Fossology, Fosslight, Barista, Philips software license-scanner, and many more.

- ScanCode.io (CLI, web UI and REST API) can read and write SPDX and CycloneDX. It embeds scancode-toolkit and and can scan for origin, vulnerabilities and license a large range of codebase including first class support for Linux containers and docker images, VM Images, Windows containers, Windows VM images as well as packages and codebase with pre-defined configurable pipelines. It detacts all archives, installed and embedded formats for packages from Maven, Pypi, Ruby, Rust cargo, Go, NuGet, Alpine, Debian and derivative, RPM distros, Windows, npm and yarn, Bower, Chef, Cocoapods, conda, cran, haxe, MSI, opam, pubspec.

Both ScanCode toolkit  and ScanCode.io are extensively based on and use package-url which is where the spec was started.

- VulnerableCode is a companion open source vulnerability database at https://public.vulnerablecode.io/ and https://github.com/nexb/vulnerablecode that is also keyed by purl. It is the only open sourcecode and open data correlated and aggregated vulnerability database I know of.

- purldb is a companion database of all the purls at https://github.com/nexB/purldb/

**Comment by ivanayov** [comment]
Thank you @david-a-wheeler and @pombredanne ! Very helpful description that saved a bunch of digging into the documentation.

Addressed in [Add ScanCode](https://github.com/ivanayov/sbom-know-how/commit/f8f59016b73918107a1a01a924ee9f6b544a8b23)
