### ISSUE TITLE
Add package-url to specs

### ISSUE THREAD

**Issue by pombredanne** [ivanayov/sbom-know-how#5]
package-url/purl is a mini spec that is used across SPDX, CycloneDX and VEX/CSAF specs and supported by most tools in the space. This can act as the glue and a useful interop identifier between all these specs and these tools.

**Comment by ivanayov** [comment]
Thanks :) Addressed in [Add PURL to specs](https://github.com/ivanayov/sbom-know-how/commit/8c820b12a8f955379917ef282ba6b658f2f62f44)
